# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Woofer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Woofer# add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/InAppMessaging'
  pod 'FirebaseFirestoreSwift'
  pod 'DLRadioButton', '~> 1.4'
end
